###################################################
# docs: https://sw.kovidgoyal.net/kitty/conf/
# themes: https://github.com/dexpota/kitty-themes
###################################################

# 主题
include ./themes/Monokai_sublime.conf

# 设置字体: https://github.com/subframe7536/Maple-font
font_family       Maple Mono NF light
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         16

# 行高/列宽
adjust_line_height    0
adjust_column_width   0

## 光标
cursor                     #4f7beb
cursor_blink_interval      2.0
cursor_stop_blinking_after 5.0

## 滚动
scrollback_lines -1

## 鼠标
copy_on_select  yes
mouse_hide_wait 2.0

## 通知
enable_audio_bell     no
visual_bell_duration  0.3
bell_on_tab           yes

## tabs 标签页
tab_bar_edge              top
tab_bar_style             powerline
tab_powerline_style       angled
inactive_tab_font_style   normal
active_tab_foreground     #f4f4f5
active_tab_background     #4f7beb
inactive_tab_foreground   #a2a5ab
inactive_tab_background   #232326
tab_bar_background        #131313
tab_title_template        "{fmt.fg.gray}{index}{fmt.fg.default}:{title}"
active_tab_title_template "{title}"

# 杂项但非常有用的设置
editor                              nvim
allow_remote_control                no
allow_hyperlinks                    no
term                                xterm-256color
macos_option_as_alt                 yes
macos_quit_when_last_window_closed  yes
strip_trailing_spaces               smart
update_check_interval               72
hide_window_decorations             titlebar-only

###################################################
#                    快捷键
###################################################
# 清除所有快捷键
clear_all_shortcuts      yes

# 复制当前命令行所有字符
map cmd+a                pipe @text tab pbcopy

# 复制
map cmd+c                copy_to_clipboard

# 粘贴
map cmd+v                paste_from_clipboard

# 上下滚动
map ctrl+alt+j           scroll_page_up
map ctrl+alt+k           scroll_page_down

# 创建一个新的tab
map cmd+t                new_tab_with_cwd !neighbor

# 下一个tab
map alt+l                next_tab

# 上一个tab
map alt+h                previous_tab

# 关闭当前tab
map alt+q                close_tab

# 设置tab标题
map alt+t                set_tab_title

# 移动 tab 到左/右边
map cmd+shift+left       move_tab_backward
map cmd+shift+right      move_tab_forward

