#  ╭──────────────────────────────────────────────────────────────────────────────╮
#  │                                   startup                                    │
#  │          https://sw.kovidgoyal.net/kitty/overview/#startup-sessions          │
#  ╰──────────────────────────────────────────────────────────────────────────────╯
#  ╭──────────────────────────────────────────────────────────────────────────────╮
#  │ tab: vifm -> run vifm                                                        │
#  ╰──────────────────────────────────────────────────────────────────────────────╯
# new_tab vifm
# layout tall
# launch zsh -c "vifm ~/Desktop/codes ~"

#  ╭──────────────────────────────────────────────────────────────────────────────╮
#  │ tab: nvim -> run nvim                                                        │
#  ╰──────────────────────────────────────────────────────────────────────────────╯
# new_tab nvim
# layout tall
# launch zsh -c "nvim"

#  ╭──────────────────────────────────────────────────────────────────────────────╮
#  │ tab: tmux -> run tmux or zellij                                              │
#  ╰──────────────────────────────────────────────────────────────────────────────╯
new_tab tmux
layout tall
launch zsh -c "tmux"
# launch zsh -c "zellij"
focus

#  ╭──────────────────────────────────────────────────────────────────────────────╮
#  │ tab: cmds -> run cmds                                                        │
#  ╰──────────────────────────────────────────────────────────────────────────────╯
# new_tab cmds
# layout tall
# cd ~/Desktop
# launch zsh
