#  ╭──────────────────────────────────────────────────────────────────────────────╮
#  │                                   startup                                    │
#  ╰──────────────────────────────────────────────────────────────────────────────╯
#  ╭──────────────────────────────────────────────────────────────────────────────╮
#  │ tab: vifm -> run vifm                                                        │
#  ╰──────────────────────────────────────────────────────────────────────────────╯
# new_tab vifm
# layout tall
# launch zsh -c "vifm ~/Desktop/codes ~"

#  ╭──────────────────────────────────────────────────────────────────────────────╮
#  │ tab: nvim -> run nvim                                                        │
#  ╰──────────────────────────────────────────────────────────────────────────────╯
# new_tab nvim
# layout tall
# launch zsh -c "nvim"

layout tall
launch zsh -c "nvim"
