#!/usr/bin/env bash
####################################################################################
# ╭──────────────────────────────────────────────────────────────────────────────╮ #
# │ spacebar                                                                     │ #
# │ https://github.com/cmacrae/spacebar                                          │ #
# │ https://github.com/cmacrae/spacebar/blob/master/examples/spacebarrc          │ #
# ╰──────────────────────────────────────────────────────────────────────────────╯ #
####################################################################################

# 显示字体
spacebar -m config text_font                   "JetBrainsMono Nerd Font Mono:Regular:12.0"
spacebar -m config icon_font                   "JetBrainsMono Nerd Font Mono:Regular:12.0"

# 颜色
spacebar -m config background_color            0xff202020
spacebar -m config foreground_color            0xffa8a8a8

# 显示位置
spacebar -m config position                    bottom
spacebar -m config display                     main

# 左右边距/填充
spacebar -m config padding_left                20
spacebar -m config padding_right               20
spacebar -m config spacing_left                25
spacebar -m config spacing_right               15

# 高度
spacebar -m config height                      25

# 开启标题
spacebar -m config title                       on

# 开启 workspace 显示/颜色显示
spacebar -m config spaces                      on
spacebar -m config spaces_for_all_displays     on
spacebar -m config space_icon                  
spacebar -m config space_icon_strip            1 2 3 4 5 6 7 8 9 10
spacebar -m config space_icon_color            0xffffab91
spacebar -m config space_icon_color_secondary  0xff78c4d4
spacebar -m config space_icon_color_tertiary   0xfffff9b0

# 开启时间/设置icon/时间格式
spacebar -m config clock                       on
spacebar -m config clock_icon                  
spacebar -m config clock_format                "%Y/%m/%d"
spacebar -m config clock_icon_color            0xffa8a8a8

# 开启电量显示/设置icon
spacebar -m config power                       on
spacebar -m config power_icon_strip             
spacebar -m config power_icon_color            0xffcd950c
spacebar -m config battery_icon_color          0xffd75f5f

# 关闭right_shell
spacebar -m config right_shell                 off
