---
session:
  name: "ws"
  attach: true

template:
  direction: Horizontal
  parts:
    - direction: Vertical # tabs bar
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical # command lines
      body: true
    # 默认隐藏底部的状态栏
    # - direction: Vertical # status bar
    #   borderless: true
    #   split_size:
    #     Fixed: 2
    #   run:
    #     plugin:
    #       location: "zellij:status-bar"

tabs:
  # runner
  - name: "runner"
    direction: Horizontal
    parts:
      - direction: Vertical
        parts:
          - direction: Horizontal
            command: { cmd: zsh, args: ["-c", "cd ~/Desktop/codes && zsh"] }
          - direction: Horizontal
      - direction: Vertical
        parts:
          - direction: Horizontal
          - direction: Horizontal
      # 在这个tab中开启底部状态栏
      - direction: Vertical
        borderless: true
        split_size:
          Fixed: 2
        run:
          plugin:
            location: "zellij:status-bar"

  # nvim
  # - name: "nvim"
  #   direction: Horizontal
  #   parts:
  #     - direction: Vertical
  #       body: true

  # ranger
  # - name: "ranger"
  #   direction: Horizontal
  #   parts:
  #     - direction: Vertical
  #       body: true

  # cmds
  - name: "cmds"
    direction: Horizontal
    parts:
      - direction: Vertical
        body: true
      # 在这个tab中开启底部状态栏
      - direction: Vertical
        borderless: true
        split_size:
          Fixed: 2
        run:
          plugin:
            location: "zellij:status-bar"
