----------------------------------------------------------------------------------
-- 配色主题: https://github.com/marko-cerovac/material.nvim
----------------------------------------------------------------------------------
-- vim.cmd[[colorscheme material]]
-- vim.g.material_style = "darker"
