#!/usr/bin/env bash
# ╭──────────────────────────────────────────────────────────────────────────────╮ #
# │ skhd                                                                         │ #
# │ example: https://github.com/koekeishiya/yabai/blob/master/examples/skhdrc    │ #
# ╰──────────────────────────────────────────────────────────────────────────────╯ #
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │ 切换窗口焦点                                                                 │
# ╰──────────────────────────────────────────────────────────────────────────────╯
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# ╭──────────────────────────────────────────────────────────────────────────────╮
# │ 移动窗口位置                                                                 │
# ╰──────────────────────────────────────────────────────────────────────────────╯
# 上下左右移动窗口
shift + alt - h : yabai -m window --warp west
shift + alt - j : yabai -m window --warp south
shift + alt - k : yabai -m window --warp north
shift + alt - l : yabai -m window --warp east

# 旋转窗口布局
alt - r         : yabai -m space --rotate 90
shift + alt - r : yabai -m space --rotate 270

# 在X/Y轴上旋转
shift + alt - x : yabai -m space --mirror x-axis
shift + alt - y : yabai -m space --mirror y-axis

#  ╭──────────────────────────────────────────────────────────────────────────────╮
#  │ 设置窗口大小                                                                 │
#  ╰──────────────────────────────────────────────────────────────────────────────╯
shift + alt - a : \
    yabai -m window --resize left:-20:0; \
    yabai -m window --resize right:-20:0

shift + alt - s : \
    yabai -m window --resize bottom:0:20; \
    yabai -m window --resize top:0:20

shift + alt - w : \
    yabai -m window --resize top:0:-20; \
    yabai -m window --resize bottom:0:-20

shift + alt - d : \
    yabai -m window --resize right:20:0; \
    yabai -m window --resize left:20:0

# 各个软件自动平分大小
shift + alt - 0 : yabai -m space --balance

#  ╭──────────────────────────────────────────────────────────────────────────────╮
#  │ 修改窗口布局方式                                                             │
#  ╰──────────────────────────────────────────────────────────────────────────────╯
# 将窗口修变为浮动窗口
shift + alt - f : \
  yabai -m window --toggle float; \
  yabai -m window --grid 8:8:1:1:6:6

# 让当前窗口全屏(MacOS 全屏)
alt - return         : yabai -m window --toggle zoom-fullscreen
shift + alt - return : yabai -m window --toggle native-fullscreen

#  ╭──────────────────────────────────────────────────────────────────────────────╮
#  │ 桌面操作                                                                     │
#  ╰──────────────────────────────────────────────────────────────────────────────╯
# 创建/关闭桌面
shift + cmd - n : yabai -m space --create
shift + cmd - d : yabai -m space --destroy

# 切换桌面
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6
cmd - 7 : yabai -m space --focus 7
cmd - 8 : yabai -m space --focus 8
cmd - 9 : yabai -m space --focus 9
cmd - 0 : yabai -m space --focus 10

# 将当前窗口发送到指定桌面(不跟随)
ctrl + shift - 1 : yabai -m window --space 1
ctrl + shift - 2 : yabai -m window --space 2
ctrl + shift - 3 : yabai -m window --space 3
ctrl + shift - 4 : yabai -m window --space 4
ctrl + shift - 5 : yabai -m window --space 5
ctrl + shift - 6 : yabai -m window --space 6
ctrl + shift - 7 : yabai -m window --space 7
ctrl + shift - 8 : yabai -m window --space 8
ctrl + shift - 9 : yabai -m window --space 9
ctrl + shift - 0 : yabai -m window --space 10

# 只移动光标,不带着当前窗口的软件移动
shift + cmd - h : yabai -m space --focus prev
shift + cmd - l : yabai -m space --focus next

# 将当前窗口发送到指定桌面(跟随)
# shift + cmd - k : yabai -m window --space prev && yabai -m space --focus prev
# shift + cmd - j : yabai -m window --space next && yabai -m space --focus next
shift + cmd - 1 : yabai -m window --space 1 && yabai -m space --focus 1
shift + cmd - 2 : yabai -m window --space 2 && yabai -m space --focus 2
shift + cmd - 3 : yabai -m window --space 3 && yabai -m space --focus 3
shift + cmd - 4 : yabai -m window --space 4 && yabai -m space --focus 4
shift + cmd - 5 : yabai -m window --space 5 && yabai -m space --focus 5
shift + cmd - 6 : yabai -m window --space 6 && yabai -m space --focus 6
shift + cmd - 7 : yabai -m window --space 7 && yabai -m space --focus 7
shift + cmd - 8 : yabai -m window --space 8 && yabai -m space --focus 8
shift + cmd - 9 : yabai -m window --space 9 && yabai -m space --focus 9
shift + cmd - 0 : yabai -m window --space 9 && yabai -m space --focus 10

# ╭──────────────────────────────────────────────────────────────────────────────╮
# │ launcher                                                                     │
# ╰──────────────────────────────────────────────────────────────────────────────╯
# 列出所有的软件: mdfind kMDItemKind=Application
# 查看软件的包名: mdls -name kMDItemCFBundleIdentifier /Applications/Safari.app
# 查看更多按键码: skhd -o
alt - 1: open -a "Finder"                               # Finder
alt - 2: open -b "com.yimutodo.app"                     # 一木清单(根据包名启动)
alt - 3: open -a "WezTerm"                              # wezterm
alt - 4: open -a "Visual Studio Code"                   # vscode
alt - 5: open -a "Typora"                               # typora
alt - 6: open -a "QQ"                                   # QQ
alt - 7: open -a "WeChat"                               # 微信
alt - 8: open -a "YesPlayMusic"                         # 网易云音乐
alt - 9: open -a "Launchpad"                            # 启动项
alt - 0: open -b "com.google.chrome"                    # Google Chrome 浏览器
alt - 0x1B: open -a "neovide" --args --frame buttonless # neovim(alt + -)
alt - 0x18: open -b "org.alacritty"                     # Alacritty

