#!/usr/bin/env bash
# ╭──────────────────────────────────────────────────────────────────────────────╮ #
# │ skhd                                                                         │ #
# │ example: https://github.com/koekeishiya/yabai/blob/master/examples/skhdrc    │ #
# ╰──────────────────────────────────────────────────────────────────────────────╯ #

# ╭──────────────────────────────────────────────────────────────────────────────╮
# │ <ESC>自动切换输入法                                                          │
# ╰──────────────────────────────────────────────────────────────────────────────╯
0x35 -> : im-select com.apple.keylayout.ABC

# ╭──────────────────────────────────────────────────────────────────────────────╮
# │ launcher                                                                     │
# ╰──────────────────────────────────────────────────────────────────────────────╯
# 列出所有的软件: sudo find / -iname "*.app"
# 查看软件的包名: mdls -name kMDItemCFBundleIdentifier /Applications/Safari.app
# 查看更多按键码: skhd -o
alt - 1: open -b "com.apple.finder"                     # Finder
alt - 2: open -b "org.mozilla.thunderbird"              # Thunderbird
alt - 3: open -b "com.github.wez.wezterm"               # wezterm
alt - 4: open -b "com.microsoft.VSCode"                 # vscode
alt - 5: open -b "com.tencent.xinWeChat"                # 微信
alt - 9: open -a "Launchpad"                            # 启动项
alt - 0: open -b "com.google.chrome"                    # Google Chrome 浏览器
# alt - 0: open -b "org.mozilla.firefox"                  # firefox 浏览器

